pimcore:
    objects:
        custom_layouts:
            definitions:
                8cf53201-2946-43e5-8c30-e034b0171d67:
                    id: 8cf53201-2946-43e5-8c30-e034b0171d67
                    name: Revise
                    description: ''
                    creationDate: 1696592493
                    modificationDate: 1696830621
                    userOwner: 2
                    classId: '2'
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: ''
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: Block
                                        title: Block
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: block
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        lazyLoading: false
                                        disallowAddRemove: false
                                        disallowReorder: false
                                        collapsible: false
                                        collapsed: false
                                        maxItems: null
                                        styleElement: ''
                                        children:
                                            -
                                                name: title
                                                title: Title
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: input
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: null
                                                columnLength: 190
                                                regex: ''
                                                regexFlags: {  }
                                                unique: false
                                                showCharCount: false
                                                width: ''
                                                defaultValueGenerator: ''
                                                datatype: data
                                            -
                                                name: number
                                                title: Number
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: numeric
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: null
                                                integer: false
                                                unsigned: false
                                                minValue: null
                                                maxValue: null
                                                unique: false
                                                decimalSize: null
                                                decimalPrecision: null
                                                width: ''
                                                defaultValueGenerator: ''
                                                datatype: data
                                            -
                                                name: email
                                                title: Email
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: email
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                defaultValue: null
                                                columnLength: 190
                                                regex: ''
                                                regexFlags: {  }
                                                unique: false
                                                showCharCount: false
                                                width: ''
                                                defaultValueGenerator: ''
                                                datatype: data
                                            -
                                                name: location
                                                title: Location
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: geopoint
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                lat: 0
                                                lng: 0
                                                zoom: 1
                                                mapType: roadmap
                                                height: 180
                                                width: ''
                                                datatype: data
                                            -
                                                name: office
                                                title: Office
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: image
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                uploadPath: ''
                                                width: ''
                                                height: ''
                                                datatype: data
                                            -
                                                name: structtable
                                                title: Structtable
                                                tooltip: ''
                                                mandatory: false
                                                noteditable: false
                                                index: false
                                                locked: false
                                                style: ''
                                                permissions: null
                                                fieldtype: structuredTable
                                                relationType: false
                                                invisible: false
                                                visibleGridView: false
                                                visibleSearch: false
                                                labelWidth: 0
                                                labelFirstCell: ''
                                                cols:
                                                    -
                                                        position: 1
                                                        key: station
                                                        label: Station
                                                        type: text
                                                    -
                                                        type: text
                                                        position: 2
                                                        key: officer
                                                        label: Officer
                                                rows:
                                                    -
                                                        position: 1
                                                        key: murgeshpalya
                                                        label: Murgeshpalya
                                                    -
                                                        position: 2
                                                        key: ram
                                                        label: Ram
                                                height: ''
                                                width: ''
                                                datatype: data
                                        layout: null
                                        datatype: data
                                    -
                                        name: consent
                                        title: Consent
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: false
                                        style: ''
                                        permissions: null
                                        fieldtype: consent
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        defaultValue: 0
                                        width: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
