pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    image_transform:
                        items:
                            -
                                method: frame
                                arguments:
                                    width: 200
                                    height: 200
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#dbc9f3'
                        medias: {  }
                        name: image_transform
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1696999194
                        creationDate: 1696999089
                        preserveAnimation: false
