pimcore:
    config_location:
        # admin_system_settings:
        #     write_target:
        #         type: 'settings-store'
        #     read_target:
        #         type: 'settings-store' 
        system_settings:
            write_target:
                type: 'settings-store'
            read_target:
                type: 'settings-store'
    general:
        domain: ''
        redirect_to_maindomain: false
        language: en
        valid_languages:
            - en
            - hi_IN
            - kn_IN
        fallback_languages:
            en: ''
            hi_IN: en
            kn_IN: en
        default_language: en
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
                hi_IN: ''
                kn_IN: ''
    objects:
        versions:
            days: null
            steps: 10
    assets:
        versions:
            days: null
            steps: 0
    email: {  }
