pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        language: en
        valid_languages:
            - en
            - hi_IN
            - kn_IN
        fallback_languages:
            en: ''
            hi_IN: en
            kn_IN: en
        default_language: en
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
                hi_IN: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
